# 1) Print numbers from 1 to 10 using a for loop.
# SOLUTION =
# for i in range(1,11):
    # print(i)
    # i+=1

# 2) Print numbers from 10 to 1 using a while loop.
# SOLUTION =
# num = 10
# while num >= 1:
#     print(num)
#     num -= 1   # Decrease by 1 in every iteration

# 3) Print all elements of a list ["apple", "banana", "grapes"] using a for loop.
# list = ["apple", "banana" , "grapes"]
# for el in list:
#     print(el)

# 4) Print each character of the string "Python" using a for loop.
# SOLUTION=
# str = "Python"
# for char in str:
#     print(char)

# 5) Print the first 5 even numbers using a loop.
# SOLUTION = 
# i = 2
# count = 0
# while count < 5:
#     print(i)
#     i+=2
#     count +=1

# 6) Calculate the sum of first n natural numbers (where n is user input).
# SOLUTION=
# n = int(input("Enter a number: "))
# sum = 0
# for i in range(1, n + 1):   # Loop from 1 to n
#     sum += i              # Add i to sum in each iteration

# print("Sum of first", n, "natural numbers is:", sum)

# 7)Print multiplication table of a number (e.g., for 5 → 5×1=5 to 5×10=50).
# SOLUTION =
# num = int(input("enter a number : "))
# table = 1
# for i in range(1,11):
#     table = num*i
#     print(table)

